### PR TITLE
linguistqm spanish translation

### PR DESCRIPTION
**Pull request by rich1n**

### CODE REVIEW

**Comment by MAKOMO** [comment]
This PR does not contain any additional translation. In case you plan to work on the translations, please contact me directly such that I can forward to you the current .ts file. PRs are not the best way to work on translations and cause a lot of additional work on our side. Thanks!

**Comment by rich1n** [comment]
I translated the on linguistQt but don't know why didn't added the translation; this is my mail ricard122@gmail.com

**Comment by rich1n** [comment]
Hey @MAKOMO, how are you? I want to continue translating the app; please. How can begin? Regards.

**Comment by MAKOMO** [comment]
Excellent! Just grab the lastest `artisan_es.ts` translation source file from here: https://github.com/artisan-roaster-scope/artisan/tree/master/src/translations. Apply your changes using QtLinguist, save the changes again to a .ts Linguist file (not the compiled .qm file!) and send it to us for integration. Thanks a lot for supporting the project!

**Pull request closed without merging**
