### PR TITLE
Option to set Event Button Sizes #361

### PR DESCRIPTION
**Pull request by FilePhil**
I have added an option to change the size of the event buttons. It`s located under "Events -> Buttons".
The value changes the minimal width of the buttons. The hight is calculated according to the previous presets.
#361

### CODE REVIEW

**Comment by MAKOMO** [comment]
Dear FilePhil,

thanks for this new PR and sorry for the delayed processing. I'd like to take this one step by step. The first part is "Settings save/load and Palettes save/load fixed". Could you please elaborate what problem is fixed by this one, in the best case with some directions to reproduce the issue.

Thanks,
Marko

**Comment by FilePhil** [comment]
Hey Marko,
The commit "Settings save/load and Palettes save/load fixed", is maybe named a bit to inconcrete in terms of what I've made there. 
I fixed only the save/load of the new intruduced variables "buttonWidth" and "buttonpaletteWidth". I corrected the source of the Values from "self." to "aw.".
Greetings, 
Phil

**Comment by FilePhil** [comment]
Hey, Is there any feedback?

**Comment by MAKOMO** [comment]
Sorry for the delay and thank you for pushing this. I finally managed to look at your PR. While in general I like the idea of user defined button sizes I feel that those have to respect the overall design of the app. Your suggestion renders those buttons in an aspect ratio rather different to the one used in other places of the app (see screenshot). I also think 3 size options (tiny, small, large) should be enough.

PR

I just implemented an alternative (commit #a5bcb71022194b9529e03c14591902f8e63b4192) that fits better to the overall design, but serves the same purpose. I hope it is fine for you that I close this PR. 

v2 1-buttons large
v2 1-buttons small (default)
v2 1-buttons tiny

**Comment by FilePhil** [comment]
Good Solution!

**Pull request closed without merging**
