### PR TITLE
Add support for VOLTCRAFT PL-125-T4

### PR DESCRIPTION
**Pull request by baderas**
I've come across a Voltcraft PL-125-T4 which is the same as the PL-125-T2 but with four channels. (I also added the support for PL-125-T2 some months ago).

I hope i'm in time for 1.2.0 which will be released tomorrow :+1:

### CODE REVIEW

**Comment by MAKOMO** [comment]
Dear Andreas,

there is a user reporting troubles communicating with his PL-125-T4

https://www.home-barista.com/home-roasting/artisan-1-4-on-way-t54223-10.html#p613726

Do you have an idea what he might do wrong? I asked that person to open an issue on the Artisan issue tracker.

**Comment by baderas** [comment]
Sorry for the late answer. 
I think the Python code of Artisan should work independently of the OS, but since the user uses Mac, I have no clou if/how the things work from driver side. I don't even know if it is recognized and setup with as a serial port correctly.

The only help I can provide are my testscripts that I wrote during development. I've created a git repo: https://github.com/baderas/pl-125-testscripts
Maybe the user can execute them (requires Python3) to see if the connection works.

Did he create an Issue for it?

**Comment by MAKOMO** [comment]
Dear Andreas,



> On 21. Nov 2018, at 09:20, Andreas Bader <notifications@github.com> wrote:
> 
> Sorry for the late answer.
> I think the Python code of Artisan should work independently of the OS, but since the user uses Mac, I have no clou if/how the things work from driver side. I don't even know if it is recognized and setup with as a serial port correctly.

Yep, that is what I thought.

> 
> The only help I can provide are my testscripts that I wrote during development. I've created a git repo: https://github.com/baderas/pl-125-testscripts
> Maybe the user can execute them (requires Python3) to see if the connection works.

It seems his issue is resolved and was actually related to some device setup!?

> 
> Did he create an Issue for it?

Yes, forgot to mention this.

https://github.com/artisan-roaster-scope/artisan/issues/267

Here he confirms that everything works for him as expected.

Thanks again for your support,
Marko

**Comment by baderas** [comment]
Hi Marko, 
I didn't look into the closed issues :1st_place_medal: 
Nice that it solved itself, but however to have the testscript online is a good thing and to have feedback from other users with other OS as well. :+1

**Pull request merged**
