### PR TITLE
Aillio Bullet R1

### PR DESCRIPTION
**Pull request by rpaulo**
This is a skeleton support for the R1.

I'm still trying to figure out how to get the USB interface working, but I wanted to create this PR because there is some interest in the community.

### CODE REVIEW

**Comment by MAKOMO** [comment]
Rui,

thanks for your work on this. So you managed to get data out of this Aillio. I am not able to test what you have done. Is it save to merge that pull?

**Comment by rpaulo** [comment]
Let me fix a few more things.  DT RoR and Drum speed isn't working yet.
I'd like to work on controlling the R1 from Artisan in a separate pull request, though.

**Comment by MAKOMO** [comment]
Ok, I'll wait for a signal from you.

**Comment by rpaulo** [comment]
So I haven't been able to figure out the drum speed yet.  The DT RoR is actually non existent so I removed that.  I have some problems with the machine template.  Can you look at it and let me know what's missing?

**Comment by MAKOMO** [comment]
The machine menu entries are just fragments of general Artisan settings. Once you are done, I'll generate a corresponding Aillio Machine menu entry. Or are you talking about the new Aillio device menu entries? What are the issue there?

**Comment by rpaulo** [comment]
I'm talking about the file in includes/Machines/Aillio.

**Comment by MAKOMO** [comment]
Ok. Easy. Could you attach a full Artisan settings file that works for you with your Aillio setup and I will generate a corresponding Machine settings file for you out of it. I have a generate for Machine files that is not checked in yet for some reasons, but will be later on.

**Comment by rpaulo** [comment]
On Sun, 2018-03-04 at 23:03 -0800, Marko Luther wrote:
> Ok. Easy. Could you attach a full Artisan settings file that works
> for you with your Aillio setup and I will generate a corresponding
> Machine settings file for you out of it. I have a generate for
> Machine files that is not checked in yet for some reasons, but will
> be later on.

OK, it's attached.

-- 
Rui Paulo

[General]
recentSettingList=@Invalid()
Geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x1N\0\0\0P\0\0\x6z\0\0\x3\x83\0\0\x1X\0\0\0}\0\0\x6p\0\0\x3y\0\0\0\0\0\0)
Mode=C
fmt_data_RoR=false
detectBackgroundEventTime=20
backgroundReproduce=false
backgroundPlaybackEvents=false
replayType=0
PhasesMode=0
PhasesEspresso=93, 149, 199, 232
PhasesFilter=93, 149, 199, 232
Phases=93, 149, 199, 232
phasesbuttonflag=false
watermarks=true
phasesLCDs=true
phasesLCDmode=1
autoDry=false
autoFCs=false
Statistics=1, 1, 0, 1, 1, 0
StatisticsConds=180, 360, 180, 600, 180, 360, 180, 300
AUCbegin=1
AUCbase=100
AUCbaseFlag=false
AUCtarget=640
AUCtargetFlag=false
AUCguideFlag=false
AUClcdFlag=false
AUCLCDmode=0
AmbientTempSource=0
Delay=1000
Oversampling=true
ExtraEventSamplingDelay=0
Colors=@Variant(\0\0\0\b\0\0\0\x19\0\0\0\f\0y\0l\0\x61\0\x62\0\x65\0l\0\0\0\n\0\0\0\b\0\x30\0.\0\x32\0\x30\0\0\0\x4\0x\0t\0\0\0\n\0\0\0\n\0g\0r\0\x65\0\x65\0n\0\0\0\f\0x\0l\0\x61\0\x62\0\x65\0l\0\0\0\n\0\0\0\b\0\x30\0.\0\x32\0\x30\0\0\0\x14\0w\0\x61\0t\0\x65\0r\0m\0\x61\0r\0k\0s\0\0\0\n\0\0\0\f\0y\0\x65\0l\0l\0o\0w\0\0\0\n\0t\0i\0t\0l\0\x65\0\0\0\n\0\0\0\b\0\x30\0.\0\x32\0\x30\0\0\0\b\0t\0\x65\0x\0t\0\0\0\n\0\0\0\n\0\x62\0l\0\x61\0\x63\0k\0\0\0 \0s\0p\0\x65\0\x63\0i\0\x61\0l\0\x65\0v\0\x65\0n\0t\0t\0\x65\0x\0t\0\0\0\n\0\0\0\n\0\x62\0l\0\x61\0\x63\0k\0\0\0\x1e\0s\0p\0\x65\0\x63\0i\0\x61\0l\0\x65\0v\0\x65\0n\0t\0\x62\0o\0x\0\0\0\n\0\0\0\f\0y\0\x65\0l\0l\0o\0w\0\0\0\n\0r\0\x65\0\x63\0t\0\x35\0\0\0\n\0\0\0\x12\0l\0i\0g\0h\0t\0g\0r\0\x65\0y\0\0\0\n\0r\0\x65\0\x63\0t\0\x34\0\0\0\n\0\0\0\x12\0l\0i\0g\0h\0t\0\x62\0l\0u\0\x65\0\0\0\n\0r\0\x65\0\x63\0t\0\x33\0\0\0\n\0\0\0\xe\0#\0\x39\0\x39\0\x36\0\x36\0\x33\0\x33\0\0\0\n\0r\0\x65\0\x63\0t\0\x32\0\0\0\n\0\0\0\f\0o\0r\0\x61\0n\0g\0\x65\0\0\0\n\0r\0\x65\0\x63\0t\0\x31\0\0\0\n\0\0\0\n\0g\0r\0\x65\0\x65\0n\0\0\0\xe\0m\0\x65\0t\0t\0\x65\0x\0t\0\0\0\n\0\0\0\n\0\x62\0l\0\x61\0\x63\0k\0\0\0\xe\0m\0\x61\0r\0k\0\x65\0r\0s\0\0\0\n\0\0\0\n\0\x62\0l\0\x61\0\x63\0k\0\0\0\x18\0l\0\x65\0g\0\x65\0n\0\x64\0\x62\0o\0r\0\x64\0\x65\0r\0\0\0\n\0\0\0\x10\0\x64\0\x61\0r\0k\0g\0r\0\x65\0y\0\0\0\x10\0l\0\x65\0g\0\x65\0n\0\x64\0\x62\0g\0\0\0\n\0\0\0\n\0w\0h\0i\0t\0\x65\0\0\0\b\0g\0r\0i\0\x64\0\0\0\n\0\0\0\xe\0#\0\x38\0\x30\0\x38\0\x30\0\x38\0\x30\0\0\0\x4\0\x65\0t\0\0\0\n\0\0\0\x6\0r\0\x65\0\x64\0\0\0\xe\0\x64\0\x65\0l\0t\0\x61\0\x65\0t\0\0\0\n\0\0\0\f\0o\0r\0\x61\0n\0g\0\x65\0\0\0\xe\0\x64\0\x65\0l\0t\0\x61\0\x62\0t\0\0\0\n\0\0\0\b\0\x62\0l\0u\0\x65\0\0\0\f\0\x63\0\x61\0n\0v\0\x61\0s\0\0\0\n\0\0\0\b\0N\0o\0n\0\x65\0\0\0\x4\0\x62\0t\0\0\0\n\0\0\0\xe\0#\0\x30\0\x30\0\x30\0\x30\0\x37\0\x66\0\0\0\x14\0\x62\0\x61\0\x63\0k\0g\0r\0o\0u\0n\0\x64\0\0\0\n\0\0\0\n\0w\0h\0i\0t\0\x65\0\0\0\n\0\x43\0l\0i\0n\0\x65\0\0\0\n\0\0\0\b\0\x62\0l\0u\0\x65)
LCDColors=@Variant(\0\0\0\b\0\0\0\x6\0\0\0\n\0t\0i\0m\0\x65\0r\0\0\0\n\0\0\0\n\0\x62\0l\0\x61\0\x63\0k\0\0\0\x4\0s\0v\0\0\0\n\0\0\0\xe\0#\0\x34\0\x30\0\x34\0\x30\0\x34\0\x30\0\0\0\x4\0\x65\0t\0\0\0\n\0\0\0\xe\0#\0\x44\0\x39\0\x44\0\x39\0\x44\0\x39\0\0\0\xe\0\x64\0\x65\0l\0t\0\x61\0\x65\0t\0\0\0\n\0\0\0\xe\0#\0\x42\0\x46\0\x42\0\x46\0\x42\0\x46\0\0\0\xe\0\x64\0\x65\0l\0t\0\x61\0\x62\0t\0\0\0\n\0\0\0\xe\0#\0\x42\0\x46\0\x42\0\x46\0\x42\0\x46\0\0\0\x4\0\x62\0t\0\0\0\n\0\0\0\xe\0#\0\x44\0\x39\0\x44\0\x39\0\x44\0\x39)
LEDColors=@Variant(\0\0\0\b\0\0\0\x6\0\0\0\n\0t\0i\0m\0\x65\0r\0\0\0\n\0\0\0\n\0w\0h\0i\0t\0\x65\0\0\0\x4\0s\0v\0\0\0\n\0\0\0\f\0y\0\x65\0l\0l\0o\0w\0\0\0\x4\0\x65\0t\0\0\0\n\0\0\0\x6\0r\0\x65\0\x64\0\0\0\xe\0\x64\0\x65\0l\0t\0\x61\0\x65\0t\0\0\0\n\0\0\0\f\0o\0r\0\x61\0n\0g\0\x65\0\0\0\xe\0\x64\0\x65\0l\0t\0\x61\0\x62\0t\0\0\0\n\0\0\0\b\0\x62\0l\0u\0\x65\0\0\0\x4\0\x62\0t\0\0\0\n\0\0\0\xe\0#\0\x30\0\x30\0\x30\0\x30\0\x37\0\x46)
ETBColor=red
BTBColor=#00007f
ETBdeltaColor=orange
BTBdeltaColor=blue
BackgroundAlpha=0.3
Flavors=Acidity, Aftertaste, Clean Cup, Head, Fragrance, Sweetness, Aroma, Balance, Body
flavorstartangle=90
colorsystem=0
sound=0
filterDropOuts=true
dropSpikes=false
swapETBT=false
minmaxLimits=false
minLimit=10
maxLimit=700
curvefilter=3
ETcurve=true
BTcurve=true
ETlcd=true
BTlcd=true
swaplcds=false
profilepath=/home/rpaulo/Documents/
settingspath=
wheelpath=
autosavepath=
externalprogram=test.py
externaloutprogram=out.py
externaloutprogramFlag=false
BTfunction=
ETfunction=
resetqsettings=0
plotcurves=, , , , , , , , 
plotcurvecolor=black, black, black, black, black, black, black, black, black
autosaveflag=0
autosavepdf=false
autosaveprefix=
LargeLCDs=false
titleshowalways=false
roastpropertiesflag=1
roastpropertiesAutoOpenFlag=0
customflavorlabels=Acidity, Aftertaste, Clean Cup, Head, Fragrance, Sweetness, Aroma, Balance, Body
appearance=
dpi=120
recentRoasts=@Invalid()
lastLoadedProfile=@Invalid()
lastLoadedBackground=
recentFileList=@Invalid()
BackgroundGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x1\xea\0\0\x1~\0\0\x4\x43\0\0\x3-\0\0\x1\xf4\0\0\x1\xa4\0\0\x4\x39\0\0\x3#\0\0\0\0\0\0)

[Device]
id=82
phidget1048_types=1, 1, 1, 1
phidget1048_async=false, false, false, false
phidget1048_changeTriggers=0.2, 0.2, 0.2, 0.2
phidget1048_dataRate=256
phidget1046_async=false, false, false, false
phidget1046_gain=1, 1, 1, 1
phidget1046_formula=1, 1, 1, 1
phidget1046_dataRate=256
phidget1045_async=false
phidget1045_changeTrigger=0.2
phidget1045_emissivity=1
phidget1200_formula=0
phidget1200_wire=0
phidget1200_async=false
phidget1200_changeTrigger=0.2
phidget1200_dataRate=250
phidgetRemoteFlag=false
phidgetServerID=
phidgetPassword=
phidgetPort=5661
phidgetRemoteOnlyFlag=false
phidget1018_async=false, false, false, false, false, false, false, false
phidget1018_dataRates=256, 256, 256, 256, 256, 256, 256, 256
phidget1018_changeTriggers=10, 10, 10, 10, 10, 10, 10, 10
controlETpid=0, 1
readBTpid=1, 2
arduinoETChannel=1
arduinoBTChannel=2
arduinoATChannel=None
ArduinoFILT=70, 70, 70, 70
useModbusPort=false
showFujiLCDs=true
PIDbuttonflag=true
Controlbuttonflag=true
yoctoRemoteFlag=false
yoctoServerID=127.0.0.1

[events]
eventsbuttonflag=0
minieventsflag=0
eventsGraphflag=2
eventsshowflag=1
clampEvents=0
renderEventsDescr=0
eventslabelschars=4
annotationsflag=1
showeventsonbt=false
showEtypes=true, true, true, true, true
autoCharge=true
autoDrop=true
markTP=true
EvalueColor=#4895CE, #49B160, #800080, #910113
EvalueTextColor=white, white, white, white
EvalueMarker=o, s, h, D
Evaluelinethickness=1, 1, 1, 1
EvalueMarkerSize=4, 4, 4, 4
Evaluealpha=0.8, 0.8, 0.8, 0.8

[Tare]
names=@Invalid()
weights=@Invalid()
idx=-1

[SerialPort]
comport=COM4
baudrate=9600
bytesize=8
stopbits=1
parity=O
timeout=1

[S7]
area=0, 0, 0, 0, 0, 0
db_nr=1, 1, 1, 1, 1, 1
start=0, 0, 0, 0, 0, 0
type=0, 0, 0, 0, 0, 0
mode=0, 0, 0, 0, 0, 0
div=0, 0, 0, 0, 0, 0
host=127.0.0.1
port=102
rack=0
slot=0

[Modbus]
comport=COM5
baudrate=115200
bytesize=8
stopbits=1
parity=N
timeout=1
PID_slave_ID=0
PID_SV_register=0
PID_p_register=0
PID_i_register=0
PID_d_register=0
PID_OFF_action=
PID_ON_action=
input1slave=0
input1register=0
input1float=false
input1bcd=false
input1code=3
input1div=0
input1mode=C
input2slave=0
input2register=0
input2float=false
input2bcd=false
input2code=3
input2div=0
input2mode=C
input3slave=0
input3register=0
input3float=false
input3bcd=false
input3code=3
input3div=0
input3mode=C
input4slave=0
input4register=0
input4float=false
input4bcd=false
input4code=3
input4div=0
input4mode=C
input5slave=0
input5register=0
input5float=false
input5bcd=false
input5code=3
input5div=0
input5mode=C
input6slave=0
input6register=0
input6float=false
input6bcd=false
input6code=3
input6div=0
input6mode=C
PIDmultiplier=0
SVmultiplier=1
littleEndianFloats=false
wordorderLittle=true
type=0
host=127.0.0.1
port=502

[Scale]
device=None
comport=/dev/cu.usbserial-FTFKDA5O
baudrate=19200
bytesize=8
stopbits=1
parity=N
timeout=1

[Color]
device=None
comport=/dev/cu.usbserial-FTFKDA5O
baudrate=115200
bytesize=8
stopbits=1
parity=N
timeout=2

[ArduinoPID]
pidOnCHARGE=false
loadRampSoakFromProfile=false
svValues=0, 0, 0, 0, 0, 0, 0, 0
svRamps=0, 0, 0, 0, 0, 0, 0, 0
svSoaks=0, 0, 0, 0, 0, 0, 0, 0
svSlider=false
svButtons=false
svMode=0
svLookahead=0
dutySteps=1
svSliderMin=-18
svSliderMax=249
svValue=199
dutyMin=-100
dutyMax=100
pidKp=36
pidKi=0.018
pidKd=5.4
pidSource=1
pidCycle=1000
pidPositiveTarget=0
pidNegativeTarget=0
invertControl=false

[PXR]
sv%3F=0
segment5soak=0
segment3sv=100
segment1ramp=3
segment1sv=100
segment5sv=100
segment7soak=0
segment2ramp=3
autotuning=0
rampsoak=0
segment1soak=0
runstandby=0
segment4ramp=3
segment3ramp=3
decimalposition=1
segment3soak=0
svlowerlimit=0
segment7ramp=3
segment4soak=0
pvinputtype=3
d=60
segment2soak=0
svupperlimit=0
rampsoakpattern=0
segment8sv=100
segment6soak=0
segment%3F=0
p=5
segment4sv=100
i=240
segment8soak=0
segment6sv=100
segment6ramp=3
pv%3F=0
segment5ramp=3
segment2sv=100
segment8ramp=3
mv1=0
rampsoakmode=0
controlmethod=0
sv0=0
segment7sv=100

[PXG4]
selectedpid=7
segment2ramp=180
selectsv=1
segment3ramp=180
segment3soak=0
d6=60
d7=60
d4=60
d5=60
d2=60
d3=60
d1=60
segment11soak=0
segment15soak=0
segment16sv=580
segment7soak=0
segment9ramp=180
p1=5
segment4soak=0
p6=5
p7=5
rampsoakpattern=6
d=60
manual=0
p=5
rampsoakmode=0
segment4ramp=180
pvinputtype=3
segment5sv=530
decimalposition=1
rampslopeunit=1
segment15ramp=180
segment5soak=0
segment3sv=350
segment1sv=270
pv%3F=0
segment14sv=570
segment14ramp=180
segment9sv=550
pvinputupperlimit=9999
segment12soak=0
segment5ramp=180
timeunits=1
controlmethod=0
segment12sv=560
segment10sv=550
segment7sv=540
segment12ramp=180
segment9soak=0
segment16ramp=180
segment16soak=0
segment11ramp=180
segment4sv=400
segment13soak=0
segment2sv=300
segment1ramp=180
autotuning=0
runstandby=0
segment15sv=580
p2=5
p3=5
segment13sv=570
segment8sv=540
segment6soak=0
p4=5
p5=5
segment6sv=530
segment6ramp=180
stat%3F=31041
pvinputlowerlimit=0
segment10ramp=180
segment11sv=560
rampsoak=0
segment1soak=0
segment7ramp=180
segment2soak=0
segment8soak=0
sv%3F=0
alarm%3F=31007
sv6=550
sv7=575
sv4=450
sv5=500
sv2=350
sv3=400
sv1=300
stat=41561
mv1=0
i1=240
i3=240
i2=240
i5=240
i4=240
i7=240
i6=240
segment14soak=0
segment10soak=0
i=240
selectpid=0
segment8ramp=180
segment13ramp=180
unitdisplay=1
fault%3F=31008
followBackground=false
lookahead=0

[deltaDTA]
sensortype=0
p=5
units=1
pv=0
d=60
controlsetting=1
i=240
error=0
sv=100
controlmethod=0

[RoC]
DeltaET=false
DeltaBT=true
DeltaETlcd=true
DeltaBTlcd=true
deltafilter=17
DeltaSpan=6
LCDdecimalplaces=0
statisticsmode=1

[DefaultButtons]
buttonvisibility=true, true, true, true, true, false, true, true
buttonactions=0, 0, 0, 0, 0, 0, 0, 0
buttonactionstrings=, , , , , , , 
extrabuttonactions=0, 0, 0
extrabuttonactionstrings=, , 
xextrabuttonactions=0, 0
xextrabuttonactionstrings=, 

[HUD]
Projection=true
ProjectionMode=0
ETtarget=149
BTtarget=93
ET2target=177
BT2target=121
Mode=0
hudETpid=5, 240, 60
buttonFlag=false

[Style]
patheffects=2
graphstyle=0
graphfont=0

[Sound]
Beep=0

[Axis]
xmin=-30
xmax=600
ymax=250
ymin=0
zmax=35
zmin=-5
resetmaxtime=600
lockmax=false
locktimex=true
autotimex=true
locktimex_start=-30
legendloc=7

[RoastProperties]
drumspeed=
operator=
roastertype=Aillio Bullet R1
densitySampleVolume=0
beansize=0

[XT]
color=green
index=0

[Units]
weight=g
volume=l
densityweight=g
densityvolume=l
volumeCalcUnit=0

[Alarms]
alarmflag=@Invalid()
alarmguard=@Invalid()
alarmnegguard=@Invalid()
alarmtime=@Invalid()
alarmoffset=@Invalid()
alarmcond=@Invalid()
alarmsource=@Invalid()
alarmtemperature=@Invalid()
alarmaction=@Invalid()
alarmbeep=@Invalid()
alarmstrings=@Invalid()
loadAlarmsFromProfile=false
alarmsfile=
alarm_popup_timout=10

[ExtraDev]
extradevices=84, 83, 85
extradevicecolor1=black, black, black
extradevicecolor2=black, black, black
extraname1=BT RoR, Heater, Voltage
extraname2=Drum, Fan, Exit temp
extramathexpression1=, , 
extramathexpression2=, , 
extraLCDvisibility1=true, true, true, false, false, false, false, false, false, false
extraLCDvisibility2=true, true, true, false, false, false, false, false, false, false
extraCurveVisibility1=true, true, true, true, true, true, true, true, true, true
extraCurveVisibility2=true, true, true, true, true, true, true, true, true, true

[ExtraComm]
extracomport=COM1, COM1, COM1
extrabaudrate=19200, 19200, 19200
extrabytesize=8, 8, 8
extraparity=E, E, E
extrastopbits=1, 1, 1
extratimeout=1, 1, 1

[CurveStyles]
BTlinestyle=-
BTdrawstyle=default
BTlinewidth=2
BTmarker=None
BTmarkersize=6
ETlinestyle=-
ETdrawstyle=default
ETlinewidth=2
ETmarker=None
ETmarkersize=6
BTdeltalinestyle=-
BTdeltadrawstyle=default
BTdeltalinewidth=2
BTdeltamarker=None
BTdeltamarkersize=6
ETdeltalinestyle=-
ETdeltadrawstyle=default
ETdeltalinewidth=2
ETdeltamarker=None
ETdeltamarkersize=6
BTbacklinestyle=-
BTbackdrawstyle=default
BTbacklinewidth=2
BTbackmarker=None
BTbackmarkersize=6
ETbacklinestyle=-
ETbackdrawstyle=default
ETbacklinewidth=2
ETbackmarker=None
ETbackmarkersize=6
XTbacklinestyle=-
XTbackdrawstyle=default
XTbacklinewidth=1
XTbackmarker=None
XTbackmarkersize=6
BTBdeltalinestyle=-
BTBdeltadrawstyle=default
BTBdeltalinewidth=2
BTBdeltamarker=None
BTBdeltamarkersize=6
ETBdeltalinestyle=-
ETBdeltadrawstyle=default
ETBdeltalinewidth=2
ETBdeltamarker=None
ETBdeltamarkersize=6
extralinestyles1=-, -, -
extralinestyles2=-, -, -
extradrawstyles1=default, default, default
extradrawstyles2=default, default, default
extralinewidths1=1, 1, 1
extralinewidths2=1, 1, 1
extramarkers1=None, None, None
extramarkers2=None, None, None
extramarkersizes1=6, 6, 6
extramarkersizes2=6, 6, 6

[background]
backgrounddetails=true
backgroundevents=true
movespeed=30
DeltaETB=false
DeltaBTB=true
alignEvent=0
ETBflag=true
BTBflag=true

[WebLCDs]
active=false
port=8080
alerts=false

[ExtraEventButtons]
buttonlistmaxlen=11
extraeventstypes=@Invalid()
extraeventsvalues=@Invalid()
extraeventsactionstrings=@Invalid()
extraeventsactions=@Invalid()
extraeventsdescriptions=@Invalid()
extraeventsvisibility=@Invalid()
extraeventslabels=@Invalid()
extraeventbuttoncolor=@Invalid()
extraeventbuttontextcolor=@Invalid()
extraeventsbuttonsflag=1
buttonpalette=@Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0), @Variant(\0\0\0\t\0\0\0\0)
buttonpalettemaxlen=14, 14, 14, 14, 14, 14, 14, 14, 14, 14
buttonpalette_shortcuts=true

[RoRlimits]
RoRlimitFlag=true
RoRlimit=35
RoRlimitm=-71

[grid]
xgrid=120
ygrid=25
zgrid=5
gridlinestyle=0
gridthickness=1
gridalpha=0.2
xrotation=0

[Sliders]
slidervisibilities=0, 0, 0, 0
slideractions=0, 0, 0, 0
slidercommands=, , , 
slideroffsets=0, 0, 0, 0
sliderfactors=1, 1, 1, 1
slidermin=0, 0, 0, 0
slidermax=100, 100, 100, 100
eventslidersflag=1
eventslidercoarse=0, 0, 0, 0

[Quantifiers]
quantifieractive=0, 0, 0, 0
quantifiersource=0, 0, 0, 0
quantifiermin=0, 0, 0, 0
quantifiermax=100, 100, 100, 100
quantifiercoarse=0, 0, 0, 0
clusterEventsFlag=false

[Batch]
batchcounter=-1
batchsequence=1
batchprefix=
lastroastepoch=1520195605

[ExtrasMoreInfo]
showmet=false
statssummary=false

**Comment by MAKOMO** [comment]
Sorry, one more quick question. Which usb lib are you using? I am a bit worried about cross-platform compatibility. I see your import of usb1. Is this https://github.com/vpelletier/python-libusb1, a quite outdated lib depending on some native driver? I found this one, https://github.com/pyusb/pyusb, a more actively developed Python native lib that might work on all Artisan platform. Is your code compatible to the later?

**Comment by MAKOMO** [comment]
Would the following Machine Setting work for your? It seems that the vpelletier lib could work cross platform. However, this will most likely require updates to the build scripts for proper bundling. One suggestion: could that one new extra device entry "Aillio Bullet R1 Voltage/Exit Temperature" be shortend somewhat, or even all of those entries? I also wonder why DT (drum temperature?) is selected for ET and not this "Exit Temperature"? One could also align the Extra Device names with the default event names to have them automatically translated like in the Probatone settings using {n} as label with n referring to the event number [1-4]. This is especially nice if one later decides to install quantifiers to map those extra curves to Artisan events an hide those extra curves completely as then they are nicer rendered using the Artisan event mechanism. But we can keep those things for later...

[General]
Delay=1000
Oversampling=true

[Device]
Controlbuttonflag=true
id=82

[ExtraDev]
extraCurveVisibility1=true, true, true, true, true, true, true, true, true, true
extraCurveVisibility2=true, true, true, true, true, true, true, true, true, true
extraLCDvisibility1=true, true, true, false, false, false, false, false, false, false
extraLCDvisibility2=true, true, true, false, false, false, false, false, false, false
extradevicecolor1=black, black, black
extradevicecolor2=black, black, black
extradevices=84, 83, 85
extramathexpression1=, , 
extramathexpression2=, , 
extraname1=BT RoR, Heater, Voltage
extraname2=Drum, Fan, Exit temp

[RoastProperties]
roastertype=Aillio Bullet R1

**Comment by rpaulo** [comment]
On Mon, 2018-03-05 at 00:46 -0800, Marko Luther wrote:
> Sorry, one more quick question. Which usb lib are you using? I am a
> bit worried about cross-platform compatibility. I see your import of
> usb1. Is this https://github.com/vpelletier/python-libusb1, a quite
> outdated lib depending on some native driver? I found this one,
> https://github.com/pyusb/pyusb, a more actively developed Python
> native lib that might work on all Artisan platform. Is your code
> compatible to the later?

No, but I can re-write it.  It does look like a better option.

**Comment by rpaulo** [comment]
On Mon, 2018-03-05 at 09:10 +0000, Marko Luther wrote:
> Would the following Machine Setting work for your?

I'll try.

>  It seems that the vpelletier lib could work cross platform. 

Yes, but let's switch to PyUSB.

> However, this will most likely require updates to the build scripts
> for proper bundling. 

Yes.

> One suggestion: could that one new extra device entry "Aillio Bullet
> R1 Voltage/Exit Temperature" be shortend somewhat, or even all of
> those entries? 

Yes, I can shorten it.

> I also wonder why DT (drum temperature?) is selected for ET and not
> this "Exit Temperature"? 

I'm not sure Exit temperature works very well.  When the roaster is not
running, the exit temperature is -67C which is very odd.  This isn't a
problem with my code because the Aillio software shows the same.
Their software works with DT  and I think that's what we should do as
well.

> One could also align the Extra Device names with the default event
> names to have them automatically translated like in the Probatone
> settings using {n} as label with n referring to the event number [1-
> 4]. This is especially nice if one later decides to install
> quantifiers to map those extra curves to Artisan events an hide those
> extra curves completely as then they are nicer rendered using the
> Artisan event mechanism. But we can keep those things for later...

Hmm, I'll take a look.

**Comment by rpaulo** [comment]
The attached config doesn't work. It says: "extra device lengths don't match".

**Comment by MAKOMO** [comment]
[Bullet R1 fixed.aset.zip](https://github.com/artisan-roaster-scope/artisan/files/1783781/Bullet.R1.fixed.aset.zip)

Sorry, this one should work. One needs additional the (dummy) entry of serial configs for those extra devices... I forgot to add them.

**Comment by MAKOMO** [comment]
Sorry, I had to add another S7 device for two more channels. So you need to renumber the Aillio by +1. Hope this does not produce too much troubles. We should soon integrate your work;)

**Comment by rpaulo** [comment]
Can you review & merge?
We can fix the other stuff in a different PR.  There's lots of work to be done still :-)

**Comment by MAKOMO** [comment]
Ok. Done. Let's see.

**Pull request merged**
