### PR TITLE
Patch 1 - Add Carmomaq Roasters 

### PR DESCRIPTION
**Pull request by gustavopradof**
Hello, I'm responsible for the automation part of Carmomaq. The settings present in artisan don't work as expected since the release in 2020 I'm posting the updated files

### CODE REVIEW

**Comment by MAKOMO** [comment]
Thanks for your PR!

What about keeping the old setups, just renamed as `Stratto 1.5 Network Legacy` and `Stratto 1.5 Serial Legacy` such that owners of such older machines can still use them?

Regarding those 4 new setups (which are all quite similar), let me ask some clarifying questions on `Masteratto 2.0.aset` which seems to be the one with the most features.

1. MODBUS Channels (menu ´Config >> Ports, 3rd tab "MODBUS"`)

There are 6 MODBUS inputs active (slave != 0) in MODBUS tab , but no extra device is defined to read those additional inputs 3-6. I assume that those registers 45, 46 and 47 hold the data for Gas, Drum and Air. This data is most likely in 0-100%, thus the "Mode" should not be "C" but the empty entry, right? What does register 49 holds, the register which is written to by slider 3 (Vent. Press)?

Defining extra devices to read this data allows to synchronise changes set by controls on the machine to the Artisan software via is event quantifiers.


2. Event Names (menu `Config >> Events, 1st tab "Config"`)

Currently the 4 event names are (english defaults in brackets)
```
 1: Ar (Air)
 2. Tambor (Drum)
 3. Vent. Press (Damper)
 4. Potencia (Burner)
```

It is preferable to keep this names in the setup by their default english terms such that the translations build into Artisan can translate them to all 20+ supported languages. Not everybody speaks Portuguese;)

The default Portuguese translations correspond with the terms used by this setup, but for
```
 3. Registro (Damper)
 4. Chama (Burner)
 ```

What exactly is "Vent. Press" referring too?
Is "Potencia" a better translation for "Burner" as "Chama" which is currently used by Artisan?


3. Event Config (menu `Config >> Events, 1st tab "Config"`)

What is the effect of sending value 2 to register 50 on OFF and value 1 to register 50 on START?


4. Event Sliders (menu `Config >> Events, 3rd tab "Sliders"`)
Are those sliders intentionally ranging from 0-120% and not just 0-100%?


5. Event Buttons (menu `Config >> Events, 2nd tab "Buttons"`)

There are 12 Event buttons defined. Could you confirm the following action on the machine side? What are the last two buttons doing?

```
 - Liga Potencia: write(1,55,1) => Burner ON
 - Desliga Potencia: write(1,55,2) => Burner OFF
 - Liga Ventilador: write(1,56,1) => Fan ON
 - Desliga Ventilador: write(1,56,2) => Fan OFF
 - Liga Cilindro: write(1,57,1) => Drum ON
 - Desliga Cilindro: write(1,57,2) => Drum OFF
 - Liga Mexedor: write(1,52,1) => Stirrer ON
 - Desliga Mexedor: write(1,52,2) => Stirrer OFF
 - Liga Resfriador: write(1,58,1) => Cooling ON
 - Desliga Resfriador: write(1,58,2) => Cooling OFF
 - Liga Vent. Pressão: write(1,60,1) =>  ??? ON
 - Desliga Vent. Pressão: write(1,60,2) => ???  OFF
```

Organizing those buttons a bit differently we could have the localized into all languages supported by Artisan.

**Comment by MAKOMO** [comment]
Are you available for testing?

**Comment by gustavopradof** [comment]
> What about keeping the old setups, just renamed as `Stratto 1.5 Network Legacy` and `Stratto 1.5 Serial Legacy` such that owners of such older machines can still use them?


These settings don't work with any equipment so I deleted it.


There are 6 MODBUS inputs active (slave != 0) in MODBUS tab , but no extra device is defined to read those additional inputs 3-6. I assume that those registers 45, 46 and 47 hold the data for Gas, Drum and Air. This data is most likely in 0-100%, thus the "Mode" should not be "C" but the empty entry, right? 

That's right, the "C" is wrong I must have configured it wrong.


What does register 49 holds, the register which is written to by slider 3 (Vent. Press)?


Masteratto contains 2 fans, one for the cyclone and the other to remove pressure from the roaster, register 49 is the pressure fan control from 0 to 120%.


What exactly is "Vent. Press" referring too?
Pressure fan.

Is "Potencia" a better translation for "Burner" as "Chama" which is currently used by Artisan?

It depends, we maintain "Potência" because we have electric and gas roasters, but for  "Burner" the correct one is "Chama"

What is the effect of sending value 2 to register 50 on OFF and value 1 to register 50 on START?

Register 50 is for starting the roaster timer, value 1 is for start and 2 for stop. 

Are those sliders intentionally ranging from 0-120% and not just 0-100%?

Yes, fan and cylinder can be adjusted from 0-120%


 - Liga Vent. Pressão: write(1,60,1) =>  pressure fan ON
 - Desliga Vent. Pressão: write(1,60,2) => pressure fan OFF

**Comment by MAKOMO** [comment]
I made a continuous build adding 4 new setups for the Carmomaq 

https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous

based on your work. 

- I reworked the custom button definition by adding groups, smoother color and labels that are translated
- I moved the timer start/end actions from START/OFF buttons to the CHARGE/DROP buttons. In Artisan the recording starts with START and ends with OFF, but the roast, while recording, starts with CHARGE (filling of the green beans into the drum) and DROP (releasing the roasted beans to the cooler). One usually records a bit before CHARGE to document the pre-heating situation and a bit after DROP to document the temperature release.
- I added extra device definitions to read the status of the actors (drum speed, air, burner level,..) and event quantifier to turn this data into event marks. That way changes made to those actors using the controls of the machine are synchronized to Artisan and properly recorded

Could you please test if those setups work as intended?

**Comment by gustavopradof** [comment]
Everything worked, both buttons and sliders.

**Comment by MAKOMO** [comment]
Thanks for checking. I will close this PR as the changes have already been added to trunk and will be part of the next release.

**Pull request closed without merging**
